name: Workflow for checking http status codes

on: [push]

jobs:
  build:
    name: HTTP Status
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP status
        uses: ./
        with:
          sites: '["http://github.com", "https://education.github.com"]'
          expected: '[301, 200]'